package mx.darthill.api.springsecurity.persistence.util;

public enum RolPermissionEnum {

    READ_ALL_VETERINARIOS,
    READ_ONE_VETERINARIOS,
    CREATE_ONE_VETERINARIOS,
    UPDATE_ONE_VETERINARIOS,
    DELETE_ONE_VETERINARIOS,

    READ_ALL_ESPECIALIDAD,
    READ_ONE_ESPECIALIDAD,
    CREATE_ONE_ESPECIALIDAD,
    UPDATE_ONE_ESPECIALIDAD,
    DELETE_ONE_ESPECIALIDAD,

    READ_PROFILE;

}
